### ISSUE TITLE
User overview transactions do not seem to be linked to the selected user

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/sudosos-frontend#100]
the `/user/{id}` page seems to show a general transaction overview instead of only the persons transactions.

**Comment by CodeNamedRobin** [comment]
Duplicate of #96

**Comment by rinkp** [comment]
So it is not completed?

**Comment by CodeNamedRobin** [comment]
Fine, duplicate of #96

**Comment by CodeNamedRobin** [comment]
Fine, duplicate of #96
