### ISSUE TITLE
Product Container Management Issues

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-frontend#119]
- [ ] Create Product Modal width should be less wide
- [ ] Alcohol Percentage should appear when creating alcoholic product
- [ ] Should be able to create product on adding product to container
- [ ] Order of containers in Tab View should make sense (maybe by amount of transactions?)
- [ ] Should be able to scroll on tab view
- [ ] All Products table is very wonky on mobile.\

**Comment by SuperVK** [comment]
Samuel is doing full re-do of Product/container management
