### ISSUE TITLE
Missing error message on too low topup

### ISSUE THREAD

**Issue by Yaneriaf** [GEWIS/sudosos-frontend#120]
Currently, payment requires a minimum topup of 10 euros, however there is nothing indicating that the topup is too low. Would be nice to make clear, either through some text added to the balance page next to the "no cash during borrel" text, or as an error message when attempting to top up an amount less than 10.

**Comment by JustSamuel** [comment]
Isn't this an issue on the old frontend? I believe it is fixed in this version.

**Comment by Yaneriaf** [comment]
fair enough
