### ISSUE TITLE
[BUG] Topping cannot secretely change to 10 euro

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#139]
Despite it being very funny, we cannot have the top up secretly change to 10 euro when putting in a value below 10 euros.

**Comment by rinkp** [comment]
> Despite it being very funny, we cannot have the top up secretly change to 10 euro when putting in a value below 10 euros.

- I agree with @SuperVK  on his second statement. We do not want to have a discussion with Mastercard about whether a member intended to top up 10 euros or not. We will almost certainly lose chargebacks as a result of that (and pay the €40 chargeback fee)

- Additionally, I propose adding a similar note as in PR GEWIS/sudosos-frontend#16
