### ISSUE TITLE
[BUG] Profile page is improperly implemented

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#151]
One issue for now, but maybe want to split this up:
- [x] You cannot toggle intensive data processing on the profile page
- [x] You have the option to change your name, but this is throws an 403
- [x] You can generate API keys, which only admins should be able to do.
- [x] Pin codes should be hidden by a password field instead of plaintext
- [x] External accounts cannot see how they are supposed to log into the POS, the sudosos number is not shown

**Comment by CodeNamedRobin** [comment]
Since the last issue is fixed now on the backend as well, this can be fixed in short notice.
