### ISSUE TITLE
Assistance with fast-forward pull requests

### ISSUE THREAD

**Issue by rinkp** [GEWIS/sudosos-frontend#164]
Since it is very hard to do fast-forwards of the main branch when merging develop into it.

![main is 1 commit ahead of develop](https://github.com/GEWIS/sudosos-frontend-vue3/assets/17340320/9f733193-f22f-4b48-bf65-6a1cc770c6f7)

Perhaps we can set up this action, but only when merging into main:
https://github.com/marketplace/actions/fast-forward-pr

When doing this right, this also allows a controlled process of the merge and deploy process.

@CodeNamedRobin

**Comment by tomudding** [comment]
It may be preferred to use https://github.com/marketplace/actions/fast-forward-merge instead, as the `fast-forward-pr` action has not been updated in ~4 years and is forced to run on a newer version of Node by GitHub.

(or we can create our own action tailored to our needs)

**Comment by SuperVK** [comment]
I have implemented it with the GH action, after a succesfull review we can test if it does what we need it to do:
https://github.com/GEWIS/sudosos-frontend/pull/205

**Comment by SuperVK** [comment]
Works, thanks you!
