### ISSUE TITLE
Transaction modal misses context about involved users

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/sudosos-frontend#168]
The transaction dialog is missing information about each transaction for whom it is. This is especially relevant for BAC members who often create transactions for others during the borrel.

![image](https://github.com/GEWIS/sudosos-frontend-vue3/assets/38660000/7d1cdc91-24ca-4c10-9efb-84a23acec28e)

**Comment by tomudding** [comment]
GH-165

**Comment by Yoronex** [comment]
Je was me net voor :(
