### ISSUE TITLE
Topping up with a negative amount causes the component to crash

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/sudosos-frontend#170]
If you type "-10" in the top up field, the component crashes.

![image](https://github.com/GEWIS/sudosos-frontend-vue3/assets/38660000/1eb1c054-a198-4112-8ff8-ffe5bf656916)

**Comment by Yoronex** [comment]
The same happens when typing "19", which is reformatted to 19,00. If you try to change that to 19,43, it won't let you. If you add a 4 between the comma and the 0 (so 19,400), the component crashes.

Maybe only format and validate the field once the field is no longer focussed, because it becomes very hard to type a specific amount.

**Comment by tomudding** [comment]
Here a nice GIF:
![2024-05-20 14-48-05(2)](https://github.com/GEWIS/sudosos-frontend-vue3/assets/4983571/27e6721e-963b-4226-8b90-b7a147edbba6)
