### ISSUE TITLE
Date in mutation table not localised

### ISSUE THREAD

**Issue by tomudding** [GEWIS/sudosos-frontend#175]
Similar to GH-173 where localisation is not done properly.

In this case the "full" date is not localised based on the selected language:
https://github.com/GEWIS/sudosos-frontend-vue3/blob/cdc992f776cfd434833b2829d2feb1f90b4f2f5d/src/components/Mutations/MutationsTableComponent.vue#L17

The "short" date "is" (hardcoded):
https://github.com/GEWIS/sudosos-frontend-vue3/blob/cdc992f776cfd434833b2829d2feb1f90b4f2f5d/src/components/Mutations/MutationsTableComponent.vue#L18-L21

**Comment by SuperVK** [comment]
Why is it bad that the "short" date is hardcoded? What would be the better option?

**Comment by tomudding** [comment]
> Why is it bad that the "short" date is hardcoded? What would be the better option?

It is not bad it is just that my initial comment was incorrectly stating that it was localised when you change the language which is not the case since it is hardcoded. I think everyone prefers the YYYY-MM-DD the `nl-NL` localisation provides so that is not something that needs to be changed imho.
