### ISSUE TITLE
[Project] Remove technical debt

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#189]
Problem: The code style is all over the place, not consistency between them despite prettier and eslint existing. 

Plan:
- [ ] Enforce eslint/prettier #218
- [x] Components hierarchy #217 
- [x] Consistent libraries #219
- [x] Common components #216 #15 
- [ ] Rework translation files #17 (Needs a proper plan of attack)

**Comment by SuperVK** [comment]
![image](https://github.com/GEWIS/sudosos-frontend-vue3/assets/31625323/b8abf55c-e563-4cde-99a9-ceac8311cdc0)
![image](https://github.com/GEWIS/sudosos-frontend-vue3/assets/31625323/3650d025-94d9-46fa-be2b-011ef26cd150)
This is the current state of the repository

**Comment by CodeNamedRobin** [comment]
ESLint is currently in one of the checks when opening a PR right? I think that can be closed as completed. We could run prettier when opening a PR as well.

**Comment by SuperVK** [comment]
Nope, that is also why eslint gives so many errors. Enabling it in the PR check will make it impossible to make PRs rn, so we need a strategy for it

**Comment by JustSamuel** [comment]
ESlint works on my machine

**Comment by SuperVK** [comment]
Don't like this issue anymore, doesn't provide much value
