### ISSUE TITLE
[Bug]: Topping over 150 doesn't show the stripe top up

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#199]
### What browsers are you seeing the problem on?

Firefox

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Dashboard

### Current behaviour

When topping up over 150, the frontend opens the modal, but stripe doesn't appear due to invalid topping up.

### Desired behaviour

Form validation before the modal opens

### Steps to reproduce

top up 200 euro's, observe you can't top up

**Comment by tomudding** [comment]
> top up 200 euro's, observe you can't top up

Note that you should be able to top-up with >150 euros if you have a negative balance (but new balance may not exceed 150 euros). Reference code can be found at [`validateStripeRequestMaximumAmount()`](https://github.com/GEWIS/sudosos-backend/blob/d64c201aac48532812b98e9f157e095a2a3ce0d2/src/service/stripe-service.ts#L70).
