### ISSUE TITLE
[Bug]: The banners on the POS don't respect the dates

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#202]
### What browsers are you seeing the problem on?

Firefox

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Point of sale

### Current behaviour

The banners just shows a single banner and doesn't change, furthermore the banner that it does show it outdated and should not be seen anymore)

### Desired behaviour

The banners should rotate, as well as only show banners that are in the correct times.

### Steps to reproduce

Upload a banner, set the date to very soon, wait until that date is over, and observe it is still shown. Furthermore, only the banner that appears first in the open banner api endpoint is displayed, the other banners are not shown.

**Comment by JustSamuel** [comment]
@SuperVK can this be closed now with #204

**Comment by SuperVK** [comment]
oh yeah, and for further reference; the bug was not what I thought it was, but it was just the active/non-active override, as well as each banner staying on for 10k seconds.
