### ISSUE TITLE
[Refactor]: Create FormInput and default Dialog components 

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/sudosos-frontend#216]
### What browsers are you seeing the problem on?

Other

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Dashboard

### Current behaviour

We are lacking a common components for general usage (such as FormInputs and Dialogs)

### Steps to reproduce

\

**Comment by SuperVK** [comment]
Completed in #290
