### ISSUE TITLE
[Feature / Refactor] Improved permissions and updated seller experience

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/sudosos-frontend#229]
When the permissions are updated in the backend we should also update them in the dashboard. 

Possibly create a "seller overview" page where seller accounts can get some key info and also check some stats. Also allow them to create products within their own containers, because I have a feeling that the current product page does not like it when your not BACPM.

**Comment by SuperVK** [comment]
I've split this out to the two underlying issues:
- Permission refactor: #265 
- Seller overview: #266
