### ISSUE TITLE
[Bug]: Unable to input decimal numbers in Safari.

### ISSUE THREAD

**Issue by Bliekje123** [GEWIS/sudosos-frontend#244]
### What browsers are you seeing the problem on?

Safari

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Dashboard

### Current behaviour

![IMG_9664](https://github.com/GEWIS/sudosos-frontend/assets/174101476/03372d41-2918-4926-9b47-f3136edf71c9)

I can not use a comma to top up my account :’( 

### Desired behaviour

Uuh idk, a button such that I can top up my account with 10,22 for instance

### Steps to reproduce

I have an iphone which might cause the issue. No experience with the code so goodluck :)

### Other information

:)

**Comment by JustSamuel** [comment]
Thanks for opening an issue, ill check it out most likely this weekend.

**Comment by SuperVK** [comment]
Fixed as per #245, thank you for the bug report! :)

**Comment by SuperVK** [comment]
Re-opened to test automatically closing of fixed issues
