### ISSUE TITLE
Disable stripe advanced fraud detection

### ISSUE THREAD

**Issue by rinkp** [GEWIS/sudosos-frontend#246]
See https://github.com/GEWIS/sudosos-frontend-2023-09-07/issues/7

These privacy concerns still exist, the reasoning as to why disabling is possible still applies, the mentioned references still work.

From https://stripe.com/docs/disputes/prevention/advanced-fraud-detection

```js
import {loadStripe} from '@stripe/stripe-js/pure';

loadStripe.setLoadParameters({advancedFraudSignals: false});
const stripePromise = await loadStripe('pk_test_XXXXXXXXXXXX');

```

**Comment by JustSamuel** [comment]
PR has been opened #247
