### ISSUE TITLE
[Bug]: Balance on `/user/[id]` page sometimes is current user's balance

### ISSUE THREAD

**Issue by rinkp** [GEWIS/sudosos-frontend#258]
### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Dashboard

### Current behaviour

**Sometimes**, when going to another user through `/user/[id]`, the balance of the signed-in user is shown instead of the `[id]` user's balance

![image](https://github.com/user-attachments/assets/29fef50d-7f03-4a26-a75b-6d0210258585)

### Desired behaviour

The expected behaviour is that the `[id]` user's balance is shown on their page

### Steps to reproduce

1. Go to `/user-overview`
2. Search for a user
3. Open the user

### Other information

What _bacpm_ and I think is happening is that one of two things happens:
1. There is a race condition, and sometimes the balance is replaced the one way, and sometimes the balance is replaced the other way
2. Something goes wrong with fetching the `[id]` user's balance and it is not shown. However, the network request was successful even when the issue occurred.

## Known workaround
I have showed the bacpm to view the network requests to see the balance. Alternatively, a CTRL+F5 works.

**Comment by CodeNamedRobin** [comment]
This seems to work on development already? We might want to update main and redeploy to see if it still is a problem.

**Comment by rinkp** [comment]
But since this balance component is a separate component, don't we simply want to remove the case where this balance component is filled with the balance of the user that is signed in?
https://github.com/GEWIS/sudosos-frontend/blob/b0d0d57be5d3d88e8c37267f0c73831df45bc9bf/apps/dashboard/src/modules/admin/components/AdminUserBalance.vue#L56
