### ISSUE TITLE
[Feature] Add a default ‘all’ category for small POS

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/sudosos-frontend#264]
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Point of sale

### What would you like?

Add a ‘All’ product category tab on the POS when the amount of products is small enough to reasonably fit on a single page (<20)

### Why is this needed?

The outside borrel and BOOM POS have very few products and thus the extra categories add a useless extra step.

**Comment by CodeNamedRobin** [comment]
Closed by #271
