### ISSUE TITLE
[Feature] Seller overview

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#266]
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Dashboard

### What would you like?

Possibly create a "seller overview" page where seller accounts can get some key info and also check some stats. Also allow them to create products within their own containers, because I have a feeling that the current product page does not like it when your not BACPM.

### Why is this needed?

Right now, only the BACPM can do these things, but ideally all sellers can do this. And it would be nice for various organs to see how much they sold during a borrel.

**Comment by CodeNamedRobin** [comment]
Closed by #302
