### ISSUE TITLE
[Feature] Endpoint for public keys

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#274]
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Dashboard

### What would you like?

https://github.com/GEWIS/sudosos-backend/pull/242

### Why is this needed?

Easier and simpler

**Comment by CodeNamedRobin** [comment]
@SuperVK what do you mean with this issue? Where do we need to rewrite things?

**Comment by SuperVK** [comment]
It's basically this, as linked in the linked PR: https://github.com/GEWIS/sudosos-backend/issues/110

But we want to fetch these env on load of the page, and then use store them somewhere. Instead of in the .env

**Comment by JustSamuel** [comment]
Has been implemented by #434
