### ISSUE TITLE
[Bug]: Mobile navbar is split into two menus

### ISSUE THREAD

**Issue by BHenkemans** [GEWIS/sudosos-frontend#275]
### What browsers are you seeing the problem on?

Firefox

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Dashboard

### Current behaviour

![image](https://github.com/user-attachments/assets/04192f24-967e-4bba-8eec-e1dc0ae0589b)

### Desired behaviour

A single menu

### Steps to reproduce

1. Go to sudosos.gewis.nl on a device with a viewport which is slim enough (e.g., a smartphone)
2. Login
3. See navbar

**Comment by SuperVK** [comment]
Should not happen on any smartphone model, not on any i've tried this on atleast, but this does happen on split views on computers and tablet views in portrait mode

**Comment by JustSamuel** [comment]
I have a solution, but its kinda akward between (960,999) width. See here #281
