### ISSUE TITLE
[Bug]:  Transaction Detail shows variable name, not the content

### ISSUE THREAD

**Issue by BHenkemans** [GEWIS/sudosos-frontend#276]
### What browsers are you seeing the problem on?

Firefox

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Dashboard

### Current behaviour

![image](https://github.com/user-attachments/assets/3db9be54-99ec-4628-a9e2-d009b3498bb9)

### Desired behaviour

Whatever text should be there

### Steps to reproduce

1. Login 
2. Select a transaction

### Other information

I am fine with this transaction being public.

**Comment by tomudding** [comment]
GH-165 😞

**Comment by BHenkemans** [comment]
> GH-165 😞

Weirdly enough, sudosos.test.gewis.nl and my local version also do not exhibit this issue... what is going on here?

**Comment by tomudding** [comment]
> Weirdly enough, sudosos.test.gewis.nl and my local version also do not exhibit this issue... what is going on here?

It smells like not deploying updates :/

**Comment by SuperVK** [comment]
yeah propegation to production is the issue, it is already fixed

**Comment by BHenkemans** [comment]
> yeah propegation to production is the issue, it is already fixed

True!
