### ISSUE TITLE
Show version of SudoSOS in the footer of the website

### ISSUE THREAD

**Issue by BHenkemans** [GEWIS/sudosos-frontend#279]
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Dashboard

### What would you like?

I´d like to be able to see what version (either a version number or a commit hash) the website is on. 

### Why is this needed?

This is inspired by #276, which should have been fixed in #165. As the issue is fixed in sudosos.test.gewis.nl  and not on sudosos.gewis.nl, I would like to see what version is running where. This way it is possible to see whether the issue persists because of not releasing the next version of SudoSOS or because it is still broken.

**Comment by tomudding** [comment]
Should probably go into the modal, does not have to be super exposed like in the POS. On the topic of the modal, it still has the old links:

https://github.com/GEWIS/sudosos-frontend/blob/7f3384125f9015de1178086fce57202a1fb495c0/apps/dashboard/src/components/footer/FooterContactModal.vue#L31-L38

**Comment by BHenkemans** [comment]
My idea was to hide it behind the copyright. So, you click on the year, then it toggles to the current branch and hash

**Comment by BHenkemans** [comment]
> My idea was to hide it behind the copyright. So, you click on the year, then it toggles to the current branch and hash

Like this!

![Screencast_20240731_201754](https://github.com/user-attachments/assets/7f19df5e-9688-4593-8334-b778e7c38e46)
