### ISSUE TITLE
[Bug]: When credit invoice is created, it looks the same as an invoice

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-frontend#292]
### What browsers are you seeing the problem on?

Firefox

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Dashboard

### Current behaviour

When PDF is generated for a credit invoice, it does not say credit invoice on the pdf.
![image](https://github.com/user-attachments/assets/6e984910-5737-41e4-91ea-a586f17d5a61)

### Desired behaviour

It needs to show credit invoice on the invoice

### Steps to reproduce

Generate credit invoice, generate pdf, open pdf.

**Comment by SuperVK** [comment]
Will be irrelevant with the new deposit/invoice method from the backend
