### ISSUE TITLE
[CI/CD] Automatic common building

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#296]
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Both

### What would you like?

It would be nice if the development of common is automatically started with the development command for dashboard/pos. And if the building of dashboard/pos also triggers a rebuilding of common.

### Why is this needed?

We can then remove the dist folder from the repo, and the dist and the source will not be different anymore

**Comment by JustSamuel** [comment]
Cant you just straight up implement methods directly from the source of common and include the directory in the typescript config?
