### ISSUE TITLE
[Bug]: New form way does not properly handle dirtiness

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#301]
### What browsers are you seeing the problem on?

Firefox

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Dashboard

### Current behaviour

The form dirty is measured on the original loading, not updated after the store is updated. 

### Desired behaviour

It should change again, the dirty is based on the original loading thing, the baseline doesn't change after changing it once

### Steps to reproduce

Go to an edit form. Edit it to something else, (observe it changes and send a network request). Then change it back to the original; nothing happens. Change it to a third option, then it does change.

**Comment by JustSamuel** [comment]
dirtiness is based on what you reset the defaults to. To re-enable the defaults you should reset the form.

**Comment by SuperVK** [comment]
ah, my bad
