### ISSUE TITLE
[Bug]: Pagination broken after searching

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#310]
### What browsers are you seeing the problem on?

Firefox

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Dashboard

### Current behaviour

After searching certain keywords, the second page instantly directs you back to the first page.

### Desired behaviour

Pagination should not be jumping around like that

### Steps to reproduce

Go on the test database, search for "Daniel" under users, click on the second page, observe that it jumps back to the first page for some reason.

**Comment by CodeNamedRobin** [comment]
I believe this is happening because of backend pagination issues. The backend, with the same search query, gives different results every different time. There are however also two events fired when clicking the next page, which I find weird as well. Needs further investigation.
