### ISSUE TITLE
[Feature] Display warning when purchasing alcohol when narrowcasting does not think it is alcoholtime yet

### ISSUE THREAD

**Issue by rinkp** [GEWIS/sudosos-frontend#322]
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Point of sale

### What would you like?

Show a warning in POS when the alcohol tab (not the product, just the tab suffices) is selected before the alcohol time has started. In line with policy, I think it is fine to not restrict the purchase (it can be someone who forgot to charge the beer yesterday), but a visual warning should help.

### Why is this needed?

Because new freshmen sometimes buy or try to buy alcohol before 16.30h, and a warning on the fridge does not suffice, because people cannot read

**Comment by SuperVK** [comment]
Closed by #347 , Thank you for creating the issue!
