### ISSUE TITLE
[Code] BalanceWithTopup @input is dirty

### ISSUE THREAD

**Issue by CodeNamedRobin** [GEWIS/sudosos-frontend#334]
The code for the BalanceWithTopup component is quite dirty, in particular the @input function. This needs to be refactored to a standalone function.

**Comment by SuperVK** [comment]
Disagree, making it a standalone function makes this less readable because you take the functionality away from where it is relevant. We also don't use the function anywhere else because that inherently doesnt make sense and will not happen. Furthermore, we do it like this everywhere:

https://github.com/GEWIS/sudosos-frontend/blob/develop/apps/dashboard/src/modules/financial/components/invoice/forms/InvoiceAddressingForm.vue#L20

**Comment by SuperVK** [comment]
Also we have way more important code smells and functionality to fix in this codebase, so I suggest to close this issue to focus first on what matters first.

**Comment by CodeNamedRobin** [comment]
I feel like you may have misunderstood me, or I just wasn't clear. What I meant was, this logic should not be in the template above, it should be in the script below. Since I am going over every component with my localisation refactor, I am just picking up these code smells and making issues for it. Maybe I can make a tracker for this issue, collecting all of the logic in templates and not script blocks? @SuperVK what do you think?

**Comment by CodeNamedRobin** [comment]
Also, @SuperVK, priority should never be a reason to close an issue, it should then get a low priority tag.

**Comment by SuperVK** [comment]
> I feel like you may have misunderstood me, or I just wasn't clear. What I meant was, this logic should not be in the template above, it should be in the script below. Since I am going over every component with my localisation refactor, I am just picking up these code smells and making issues for it. Maybe I can make a tracker for this issue, collecting all of the logic in templates and not script blocks? @SuperVK what do you think?

No that is what I understood, hence my "the functionality away from where it is relevant." comment, and my reference to the all the other components that were introduced recently that also use this way of writing the code.

**Comment by SuperVK** [comment]
> Also, @SuperVK, priority should never be a reason to close an issue, it should then get a low priority tag.

Disagree, that is how you get a repository with 100 open issues which are completely not relevant, this makes it super difficult to manage the issues. There is a priority in tickets but sometimes they are just below "low" and need to be closed. More issues also make it harder to keep track of issues which are still relevant in the codebase. This code needs be re-done eitherway with the form refactor and people are going to forget this issue (and others like it).

**Comment by SuperVK** [comment]
Talked in real life, we will make a tracker issue for these type of issues!
