### ISSUE TITLE
[Feature] EAN Authentication

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/sudosos-frontend#352]
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Point of sale

### What would you like?

Implementation of EAN Authentication on the point of sale. It should simply allow users to scan an EAN code on the POS login page, either directly or after clicking a button.

If time permits, it would also be nice if EAN codes can be scanned when logged in. Especially users that already have a SudoSOS account and got a voucher, often log in first and then scan an EAN code. In this case, I would simply have the voucher selected as the "create a transaction for". Then, we can also log which person created a transaction on the voucher.

### Why is this needed?

Allows the usage of vouchers (borrelkaarten) on the POS.

### Other information

The backend implementation still misses some stuff, like automatically creating EAN authenticators for vouchers and generating voucher printables, but these will get a much higher priority if the POS supports vouchers.

**Comment by JustSamuel** [comment]
Already implemented - closed.
