### ISSUE TITLE
[Feature] Improve link sharing of `sudosos.gewis.nl`

### ISSUE THREAD

**Issue by JustSamuel** [GEWIS/sudosos-frontend#355]
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Both

### What would you like?

WhatsApp, Facebook and other social media sites use OpenGraph tags to add context to a link. It might be nice to add the SudoSOS logo to it, as it comes across as more "professional".

Our sad link:
![image](https://github.com/user-attachments/assets/f96d8bfb-6aee-4575-a998-81a310f3cb9a)

Chad GitHub link with image:
![image](https://github.com/user-attachments/assets/6f161fc7-c522-40af-b108-9db681515db8)

### Why is this needed?

Looks cool (and I think looking into how the whatsapp sharing thingy works is also quite interesting)

### Other information

https://stackoverflow.com/questions/19778620/provide-an-image-for-whatsapp-link-sharing

**Comment by SuperVK** [comment]
Completed via #389
