### ISSUE TITLE
[Feature] Ability to click through from the fine overview

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#357]
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Dashboard

### What would you like?

It would be nice to be able to directly open a user's page from the fine overview, for checking more detail about their account. Similar to the user overview.

### Why is this needed?

This is needed because for example the BAC treasurer would like to check for each fine user if they are fully eligible or similar

**Comment by CodeNamedRobin** [comment]
Closed by #456.
