### ISSUE TITLE
[Feature] Partially waive user's fines

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/sudosos-frontend#359]
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Dashboard

### What would you like?

Instead of waiving all user's fines, the BACPM should be able to waive them partially.

### Why is this needed?

This is a workflow that has been decided upon during a Kasco meeting. The BACPM needs this to partially waive abysmally high fines from certain users, such that they can pay of their remaining debt. This is a blocking issue for the BACPM, so it has pretty high priority.

It requires the following changes:
- [ ] When waiving fines, the BACPM should get a dialog asking how much should be waived (the total amount of fines by default).
- [ ] If not present already, this amount should be explicitly confirmed, as it is a destructive operation which (in some cases) cannot be undone.
- [ ] For users, their fine should be shown as `BalanceResponse.fine - BalanceResponse.fineWaived` (if the latter is present).
- [ ] For BACPM (admins), both a user's fine and the amount waived should be shown seperately.

What I can think of, no other workflows need to be changed. Also take a look at the PRs mentioned below, as there contain more details about the workflow changes.

### Other information

Depends on https://github.com/GEWIS/sudosos-backend/pull/344 and https://github.com/GEWIS/sudosos-backend/pull/345.

**Comment by SuperVK** [comment]
Completed as per #429
