### ISSUE TITLE
[Feature] Flag transaction button

### ISSUE THREAD

**Issue by Yoronex** [GEWIS/sudosos-frontend#360]
### Is this a feature for the SudoSOS point of sale or for the SudoSOS dashboard?

Dashboard

### What would you like?

A "Flag transaction" button in the transaction details dialog, that is actually a `mailto` link to the BACPM with all relevant/necessary information present in the email template.

### Why is this needed?

This makes it easier for users to request a correction, as they know who to contact. Furthermore, such a button also makes the BACPM's life easier, as we can include the necessary information like SudoSOS ID, GEWIS ID, transaction ID, etc in the email template.

### Other information

Should we hardcode the BACPM email address? Webscrapers can easily find the email address if we hardcode it in this repository. If not, are we going to put this email address in an environment variable of the frontend, or as an endpoint of the backend?

**Comment by SuperVK** [comment]
right now in the contact modal they are also already hardcoded, but might make more sense to put it in an env variable?

**Comment by SuperVK** [comment]
Closed via #363
