### ISSUE TITLE
[Bug]: No feedback on POS when cannot go into debt

### ISSUE THREAD

**Issue by SuperVK** [GEWIS/sudosos-frontend#430]
### What browsers are you seeing the problem on?

Firefox

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Point of sale

### Current behaviour

When you want to checkout as user that cannot go into debt, but you will go into debt with this transaction, the POS does not give any feedback on this and silently fails.

### Desired behaviour

Give some information on why, and how to resolve by topping up. 

### Steps to reproduce

Have an account that cannot go into debt, and then select a product that makes you go into the minus.

**Comment by SvenMokveldje** [comment]
fixed in PR #457
