### ISSUE TITLE
[Bug]: Incorrect credit/debit after purchase displayed when charging different user

### ISSUE THREAD

**Issue by RubenLWF** [GEWIS/sudosos-frontend#432]
### What browsers are you seeing the problem on?

Firefox

### Is this happening on the SudoSOS point of sale or on the SudoSOS dashboard?

Point of sale

### Current behaviour

Recently, when purchasing something on the POS on behalf of someone else, I noticed that the credit after purchase was displayed incorrectly. It displayed my balance with the purchase amount subtracted from it, rather than the new balance of the person actually paying.

Currently, at the bottom of the cart, the following is displayed:
![image](https://github.com/user-attachments/assets/702ad7d2-21d8-40cf-8c9c-e22ec70153a0)

When you change the user that is being charged, the debit/credit after purchase stays the same:
![test](https://github.com/user-attachments/assets/ca6be016-f671-4adb-a6a4-2e0178425979)

I have noticed that a request is sent to the `/v1/balances/{userId}` endpoint that is answered by a `403 Unauthorized` response.
I suspect this has something to do with the fact that not everyone is allowed to request a users balance (?)

### Desired behaviour

I expect the correct new balance to be displayed when making a purchase.

I understand that this might a privacy concern since you will be able to see everyone's balance, so it might be better to not display the credit/debit after purchase as soon as you are not purchasing something for yourself.

### Steps to reproduce

1. Log into the POS
2. Change who the order is for

(See GIF above)

**Comment by JustSamuel** [comment]
Can I set you as assignee 👀👀

**Comment by JustSamuel** [comment]
Also, IIRC, this _does_ work when in Borrel mode? (which is a needed feature)

Might be a good idea to just hide it when not in borrelmode

**Comment by RubenLWF** [comment]
> Also, IIRC, this _does_ work when in Borrel mode? (which is a needed feature)
> 
> Might be a good idea to just hide it when not in borrelmode

That's indeed what I found when looking through the code.

I think it should only be visible when you are making a purchase for yourself, or when in borrelmode.
