### ISSUE TITLE
formatPrice utility inputs number, not Dinero

### ISSUE THREAD

**Issue by BHenkemans** [GEWIS/sudosos-frontend#56]
The formatPrice function in the formatterUtils.ts file takes number as input. It would probably be better if the function uses Dinero, then the currency information could also be pulled from the Dinero object!

**Comment by BHenkemans** [comment]
@CodeNamedRobin, could you look into this? It is your code and I believe you have a reason for doing this.

**Comment by CodeNamedRobin** [comment]
The reason for doing this was because I was a noob when i wrote this code. But this is a duplicate/addition to #22 so I will close this one.
