### ISSUE TITLE
Quick overview for bar staff

### ISSUE THREAD

**Issue by rinkp** [GEWIS/sudosos-frontend#7]
This means the bar committee no longer has to ask for members to spell their name (which given the noise may take quite a bit of time) and also works for members who chose to not have a membership card.

![image](https://github.com/GEWIS/sudosos-frontend-vue3/assets/17340320/48afce6e-2e25-43f3-9fc3-669989a8ed9c)

**Comment by rinkp** [comment]
It only makes sense to show on mobile devices

**Comment by JustSamuel** [comment]
Implemented a solution in this [PR](https://github.com/GEWIS/sudosos-frontend-vue3/pull/97) and I proved a screenshot of how it looks. What do you think @rinkp ?

![image](https://github.com/GEWIS/sudosos-frontend-vue3/assets/8006954/76fb11fe-5b9e-449b-a889-ea6d4cb943a5)

**Comment by rinkp** [comment]
Looks good to me
