### ISSUE TITLE
Change error message to ask people to open an issue

### ISSUE THREAD

**Issue by BHenkemans** [GEWIS/sudosos-frontend#91]
As requested by @rinkp, he asked to change the error message to ask people to open an issue and make a pull request since he is afraid that contacting team SudoSOS will not result in issues being properly handled.

**Comment by BHenkemans** [comment]
Since he suggested it; he can open a pull request with his suggestion!

**Comment by tomudding** [comment]
https://github.com/GEWIS/sudosos-frontend-vue3/issues/new?title=An+error+occurred:+ABC&body=Page%20visited%3A%0A%0Asome%20page%0A%0AStacktrace%3A%0A%0ASome%20error%0A%0AWhat%20did%20you%20do%3F%0A%0A%5Bfill%20in%5D

![image](https://github.com/GEWIS/sudosos-frontend-vue3/assets/4983571/dc2f1033-2450-40fd-bb9b-6f6225eb264f)

Or use a template
